apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dnbservicev1
  title: Create a DnB Service
  description: An template for the scaffolder that creates a DnB service
  tags:
    - django
    - harness
    - dnb
spec:
  owner: diego.pereira@harness.io
  type: service
  parameters:
    - title: DnB Service Details
      required:
        - gitUser
        - triggerPipelines
      properties:
        gitUser:
          type: string
          title: GitHub User
          description: GitHub User
          default: ''
        triggerPipelines:
          type: string
          title: Trigger Pipelines
          description: Should it Trigger Pipelines? (true/false)
          enum: ["true", "false"]
          default: 'true'
    - title: Service Infrastructure Details
      required:
        - provider
        - db
        - cache
        - lint
        - owner
      properties:
        provider:
          title: Choose a cloud provider for Deployment
          type: string
          enum: ['GCP', 'AWS', "AZURE"]
          default: GCP
        db:
          title: Choose a Database Type for the Service
          type: string
          enum: ['None', 'MySQL', 'Postgres', 'MongoDB']
          default: None
        cache:
          title: Choose a caching system for the Service
          type: string
          enum: ['None', 'Redis']
          default: None
        lint:
          title: Choose a Python linter for the Service
          type: string
          enum: ['None', 'Black', 'Flake8']
          default: None
        owner:
          title: Choose an Owner for the Service
          type: string
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
  steps:
    # Call Harness Pipelines to create the service infra and other things
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: 'Hello, ${{ parameters.gitUser }}!'
    - id: log-message-2
      name: Log Message 2
      action: debug:log
      input:
        message: 'Creating your Harness Banking Demo App Environment'
    - id: trigger
      name: Onboarding Harness Banking Demo
      action: trigger:harness-custom-pipeline
      input:
        url: 'https://app.harness.io/ng/account/6_vVHzo9Qeu9fXvj-AcbCQ/cd/orgs/default/projects/GIT_FLOW_DEMO/pipelines/Onboarding_Pipeline/pipeline-studio/?repoIdentifier=gitopsdemo&branch=main'
        inputset:
          gitUser: ${{ parameters.gitUser }}
          triggerPipelines: ${{ parameters.triggerPipelines }}
        apikey: ${{ parameters.token }}
    - id: log-message-finished
      name: Log Message 3
      action: debug:log
      input:
        message: 'Thank you! You are ready to start!'
